image:
  name: docker/compose:1.25.0-rc1
        #name: rohitgabriel/aws-compose:configuredsh
  entrypoint: ["/bin/sh", "-c"]

variables:
        #REPOSITORY_URL: rohitgabriel
  REPOSITORY_URL: ${DOCKER_REGISTRY}
services:
- docker:dind
stages:
- build
- deploy
before_script:
        #- pip install docker-compose
        - export DOCKER_REGISTRY=rohitgabriel
build:
  stage: build
  script:
          #- aws ecr get-login --no-include-email --region ap-southeast-2
     - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
     - docker-compose build
     - docker-compose push
    # - docker system prune -f -a
  only:
  - master
    #- /^build_.*$/i
  tags:
          #  - gitlab-ci-host-runner
  - docker-gitlab-ci

deploy_staging:
  stage: deploy
  image: kroniak/ssh-client:3.6
  script:
    # add the server as a known host
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    # log into Docker registry
    - ssh jenkins@ec2-13-237-19-96.ap-southeast-2.compute.amazonaws.com "docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD registry.hub.docker.com/$DOCKER_REGISTRY"
    # stop container, remove image.
    #- ssh jenkins@ec2-13-237-19-96.ap-southeast-2.compute.amazonaws.com 'docker stop $(docker ps -aq)'
    #- ssh jenkins@ec2-13-237-19-96.ap-southeast-2.compute.amazonaws.com 'docker rm $(docker ps -aq)'
    - ssh jenkins@ec2-13-237-19-96.ap-southeast-2.compute.amazonaws.com "docker stop eit_logstash_${CI_COMMIT_REF_SLUG}" || true
    - ssh jenkins@ec2-13-237-19-96.ap-southeast-2.compute.amazonaws.com "docker rm eit_logstash_${CI_COMMIT_REF_SLUG}" || true
    - ssh jenkins@ec2-13-237-19-96.ap-southeast-2.compute.amazonaws.com "docker rmi $DOCKER_REGISTRY:${CI_COMMIT_REF_SLUG}" || true
    # start new container
    - ssh jenkins@ec2-13-237-19-96.ap-southeast-2.compute.amazonaws.com "docker run --name eit_logstash_${CI_COMMIT_REF_SLUG} -d registry.hub.docker.com/$DOCKER_REGISTRY/logstash:${CI_COMMIT_REF_SLUG}"
  only:
    - master
  tags:
    - docker-gitlab-ci
      #except:
      #- master
    #deploy:
    #stage: deploy
    #script:
    #- docker run -d  ${DOCKER_REGISTRY}/logstash:latest --docker-volumes '/var/run/docker.sock:/var/run/docker.sock'
    #- docker-compose up -d
    #only:
    #- master
    #tags:
    #- docker-gitlab-ci 
